private_keys = [
    "Paste Here"
]

# DON'T CHANGE THIS VALUE !!! | JANGAN DI GANTI BAWAH INI KOCAK NANTI ERROR NANGIS -_-
VALUE_ETH = "0.002"  
GAS_LIMIT_ADJUSTMENT = 200000  
FEE_GWEI = "10"  
